package ui;

import DAO.DocGiaDAO;
import Helper.PlaceHolder;
import DAO.TaiKhoanDAO;
import DAO.NhanVienDAO;
import DTO.DocGiaDTO;
import DTO.TaiKhoanDTO;
import DTO.NhanVienDTO;
import javax.swing.JPasswordField;
import javax.swing.JOptionPane;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.sql.SQLException;
import java.util.List;
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        PlaceHolder.addPlaceHolderEffect(txMatKhau,"Nhập mật khẩu");
        PlaceHolder.addPlaceHolderEffect(txTaiKhoan,"Nhập tên đăng nhập/ Mã thẻ");
        
        btnDangnhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangnhapActionPerformed(evt);
            }
        });
         setupPlaceholders();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txTaiKhoan = new javax.swing.JTextField();
        btnDangnhap = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txMatKhau = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 500));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 3));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel4.setText("Thư viện điện tử");

        txTaiKhoan.setFont(new java.awt.Font("Arial", 2, 15)); // NOI18N
        txTaiKhoan.setForeground(new java.awt.Color(153, 153, 153));
        txTaiKhoan.setText("Nhập tên đăng nhập/ Mã thẻ");

        btnDangnhap.setBackground(new java.awt.Color(0, 122, 77));
        btnDangnhap.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        btnDangnhap.setForeground(new java.awt.Color(255, 255, 255));
        btnDangnhap.setText("Đăng nhập");
        btnDangnhap.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(242, 242, 242), 3));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logomini.png"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/decor_log.png"))); // NOI18N

        txMatKhau.setFont(new java.awt.Font("Arial", 2, 15)); // NOI18N
        txMatKhau.setForeground(new java.awt.Color(153, 153, 153));
        txMatKhau.setText("Nhập mật khẩu");
        txMatKhau.setToolTipText("");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDangnhap, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txTaiKhoan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(63, 63, 63)
                            .addComponent(jLabel4)))
                    .addComponent(txMatKhau, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(btnDangnhap, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

      private void setupPlaceholders() {
        // Placeholder cho text field tài khoản
        PlaceHolder.addPlaceHolderEffect(txTaiKhoan, "Nhập tên đăng nhập/ Mã thẻ");
        
        // Xử lý placeholder cho JPasswordField
        txMatKhau.setText("Nhập mật khẩu");
        txMatKhau.setEchoChar((char) 0); // Hiển thị text bình thường cho placeholder
        
        txMatKhau.addFocusListener(new FocusAdapter() {
            @Override
            public void focusGained(FocusEvent e) {
                if (String.valueOf(txMatKhau.getPassword()).equals("Nhập mật khẩu")) {
                    txMatKhau.setText("");
                    txMatKhau.setEchoChar('•'); // Đặt lại dấu hiệu ẩn cho mật khẩu
                }
            }
            
            @Override
            public void focusLost(FocusEvent e) {
                if (String.valueOf(txMatKhau.getPassword()).isEmpty()) {
                    txMatKhau.setEchoChar((char) 0); // Hiển thị text bình thường cho placeholder
                    txMatKhau.setText("Nhập mật khẩu");
                }
            }
        });
    }
      
    private void btnDangnhapActionPerformed(java.awt.event.ActionEvent evt) {
    String nhapVao = txTaiKhoan.getText().trim();
    String matKhau = String.valueOf(txMatKhau.getPassword()).trim();

    if (nhapVao.equals("Nhập tên đăng nhập/ Mã thẻ") || matKhau.equals("Nhập mật khẩu")) {
        JOptionPane.showMessageDialog(this, "Vui lòng nhập tên đăng nhập/mã thẻ và mật khẩu!", "Lỗi đăng nhập", JOptionPane.ERROR_MESSAGE);
        return;
    }

    if (!matKhau.equals("123456789")) {
        JOptionPane.showMessageDialog(this, "Sai mật khẩu mặc định!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        return;
    }

    try {
        TaiKhoanDAO taiKhoanDAO = new TaiKhoanDAO();
        TaiKhoanDTO tk = taiKhoanDAO.kiemTraDangNhap(nhapVao, matKhau);

        if (tk != null) {
            this.dispose();

            if (tk.getMaNhanVien() != null) {
                // → Admin
                NhanVienDAO nvDAO = new NhanVienDAO();
                NhanVienDTO nv = nvDAO.layThongTinNhanVien(tk.getMaNhanVien());
                UIa adminUI = new UIa();
                adminUI.setTaiKhoan(tk, nv.getTenNhanVien());
                adminUI.setVisible(true);

            } else if (tk.getMaThe() != null) {
                // → Độc giả
                DocGiaDAO dgDAO = new DocGiaDAO();
                DocGiaDTO dg = dgDAO.getList().stream()
                    .filter(d -> d.getMaThe().equals(tk.getMaThe()))
                    .findFirst()
                    .orElse(null);

                if (dg != null) {
                    UIu userUI = new UIu();
                    userUI.setDocGia(dg);
                    userUI.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(this, "Không tìm thấy độc giả!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Không tìm thấy tài khoản!", "Lỗi đăng nhập", JOptionPane.ERROR_MESSAGE);
        }

    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Lỗi hệ thống: " + ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        ex.printStackTrace();
    }
}
      

      
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangnhap;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField txMatKhau;
    private javax.swing.JTextField txTaiKhoan;
    // End of variables declaration//GEN-END:variables
}
