/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;


import DTO.PhanQuyenDTO;
import DAO.PhanQuyenDAO;
import Helper.PlaceHolder;
import java.awt.CardLayout;
import java.awt.Font;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.JTableHeader;
import java.util.*;
import javax.swing.*;
import java.sql.*;
import javax.swing.table.*;
/**
 *
 * @author dinhp
 */
public class PhanquyenGUI extends javax.swing.JPanel {


    public PhanquyenGUI() {
        initComponents();
        
        Giaodien.setLayout(new CardLayout());
        Giaodien.add(XemPhanquyen, "Xem");
        Giaodien.add(ThemPhanquyen, "Them");
     
        JTableHeader header = tbPhanquyen.getTableHeader(); 
        header.setFont(new Font("Arial", Font.BOLD, 16));
        ((DefaultTableCellRenderer) header.getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);
          
            PlaceHolder.addPlaceHolderEffect(txtNhapten,"Nhập tên cho phân quyền");
 // Add this line to connect the button to the action handler
    btnThemquyen.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnThemquyenActionPerformed(evt);
        }
    });
    
       loadPhanQuyenTable();
btnChitiet.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnChitietChuyenChitietActionPerformed(evt);
    }
});

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ThanhChucnang = new javax.swing.JPanel();
        btnXem = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnXoaphieu = new javax.swing.JButton();
        btnChitiet = new javax.swing.JButton();
        Giaodien = new javax.swing.JPanel();
        XemPhanquyen = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbPhanquyen = new javax.swing.JTable();
        ThemPhanquyen = new javax.swing.JPanel();
        PanPhanquyen = new javax.swing.JPanel();
        Nhapten = new javax.swing.JLabel();
        txtNhapten = new javax.swing.JTextField();
        Quanlychucnang = new javax.swing.JLabel();
        txQuanlysach = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        txQuanlynhanvien = new javax.swing.JLabel();
        txQuanlyphieunhapsach = new javax.swing.JLabel();
        txQuanlydocgia = new javax.swing.JLabel();
        txQuanlyphanquyen = new javax.swing.JLabel();
        txQuanlyphieumuon = new javax.swing.JLabel();
        txQuanlytaikhoan = new javax.swing.JLabel();
        txQuanlythongke = new javax.swing.JLabel();
        txQuanlynguonnhap = new javax.swing.JLabel();
        Quanlysach = new javax.swing.JCheckBox();
        Quanlynhanvien = new javax.swing.JCheckBox();
        Quanlyphieunhapsach = new javax.swing.JCheckBox();
        Quanlydocgia = new javax.swing.JCheckBox();
        Quanlyphanquyen = new javax.swing.JCheckBox();
        Quanlyphieumuon = new javax.swing.JCheckBox();
        Quanlytaikhoan = new javax.swing.JCheckBox();
        Quanlythongke = new javax.swing.JCheckBox();
        Quanlynguonnhap = new javax.swing.JCheckBox();
        btnCapnhat = new javax.swing.JButton();
        btnThemquyen = new javax.swing.JButton();

        jPanel1.setPreferredSize(new java.awt.Dimension(1210, 640));

        ThanhChucnang.setBackground(new java.awt.Color(255, 255, 255));
        ThanhChucnang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 3));

        btnXem.setBackground(new java.awt.Color(153, 153, 153));
        btnXem.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        btnXem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/view.png"))); // NOI18N
        btnXem.setText("Xem");
        btnXem.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnXem.setContentAreaFilled(false);
        btnXem.setFocusPainted(false);
        btnXem.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnXem.setMaximumSize(new java.awt.Dimension(50, 72));
        btnXem.setMinimumSize(new java.awt.Dimension(50, 72));
        btnXem.setPreferredSize(new java.awt.Dimension(50, 72));
        btnXem.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnXem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemChuyenXem(evt);
            }
        });

        btnThem.setBackground(new java.awt.Color(153, 153, 153));
        btnThem.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/add.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnThem.setContentAreaFilled(false);
        btnThem.setFocusPainted(false);
        btnThem.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnThem.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemChuyenThem(evt);
            }
        });

        btnXoaphieu.setBackground(new java.awt.Color(153, 153, 153));
        btnXoaphieu.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        btnXoaphieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/delete_i.png"))); // NOI18N
        btnXoaphieu.setText("Xóa phân quyền");
        btnXoaphieu.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnXoaphieu.setContentAreaFilled(false);
        btnXoaphieu.setFocusPainted(false);
        btnXoaphieu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnXoaphieu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnXoaphieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaphieuActionPerformed(evt);
            }
        });

        btnChitiet.setBackground(new java.awt.Color(153, 153, 153));
        btnChitiet.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        btnChitiet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/chitiet.png"))); // NOI18N
        btnChitiet.setText("Chi tiết");
        btnChitiet.setToolTipText("");
        btnChitiet.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnChitiet.setContentAreaFilled(false);
        btnChitiet.setFocusPainted(false);
        btnChitiet.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnChitiet.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnChitiet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChitietChuyenChitiet(evt);
            }
        });

        javax.swing.GroupLayout ThanhChucnangLayout = new javax.swing.GroupLayout(ThanhChucnang);
        ThanhChucnang.setLayout(ThanhChucnangLayout);
        ThanhChucnangLayout.setHorizontalGroup(
            ThanhChucnangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ThanhChucnangLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnXem, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnXoaphieu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnChitiet, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        ThanhChucnangLayout.setVerticalGroup(
            ThanhChucnangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ThanhChucnangLayout.createSequentialGroup()
                .addGroup(ThanhChucnangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnXem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoaphieu, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChitiet, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        Giaodien.setLayout(new java.awt.CardLayout());

        tbPhanquyen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tbPhanquyen.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        tbPhanquyen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mã phân quyền", "Tên quyền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbPhanquyen.setGridColor(new java.awt.Color(0, 0, 0));
        tbPhanquyen.setRowHeight(35);
        tbPhanquyen.setSelectionBackground(new java.awt.Color(204, 204, 204));
        tbPhanquyen.setShowVerticalLines(true);
        jScrollPane1.setViewportView(tbPhanquyen);

        javax.swing.GroupLayout XemPhanquyenLayout = new javax.swing.GroupLayout(XemPhanquyen);
        XemPhanquyen.setLayout(XemPhanquyenLayout);
        XemPhanquyenLayout.setHorizontalGroup(
            XemPhanquyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1184, Short.MAX_VALUE)
        );
        XemPhanquyenLayout.setVerticalGroup(
            XemPhanquyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(XemPhanquyenLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 83, Short.MAX_VALUE))
        );

        Giaodien.add(XemPhanquyen, "Xem");

        PanPhanquyen.setBackground(new java.awt.Color(255, 255, 255));
        PanPhanquyen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 3));
        PanPhanquyen.setPreferredSize(new java.awt.Dimension(930, 270));

        Nhapten.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        Nhapten.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Nhapten.setText("Nhập tên quyền:");

        txtNhapten.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNhapten.setText("jTextField1");
        txtNhapten.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        Quanlychucnang.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Quanlychucnang.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Quanlychucnang.setText("Quản lý chức năng");
        Quanlychucnang.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        txQuanlysach.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        txQuanlysach.setText("Quản lý sách");

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        txQuanlynhanvien.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        txQuanlynhanvien.setText("Quản lý nhân viên");

        txQuanlyphieunhapsach.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        txQuanlyphieunhapsach.setText("Quản lý phiếu nhập sách");

        txQuanlydocgia.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        txQuanlydocgia.setText("Quản lý độc giả");

        txQuanlyphanquyen.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        txQuanlyphanquyen.setText("Quản lý phân quyền");

        txQuanlyphieumuon.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        txQuanlyphieumuon.setText("Quản lý phiếu mượn");

        txQuanlytaikhoan.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        txQuanlytaikhoan.setText("Quản lý tài khoản");

        txQuanlythongke.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        txQuanlythongke.setText("Quản lý thống kê");

        txQuanlynguonnhap.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        txQuanlynguonnhap.setText("Quản lý nguồn nhập");

        btnCapnhat.setBackground(new java.awt.Color(255, 204, 0));
        btnCapnhat.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        btnCapnhat.setText("Cập nhật");
        btnCapnhat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(242, 242, 242), 3));

        btnThemquyen.setBackground(new java.awt.Color(0, 122, 77));
        btnThemquyen.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        btnThemquyen.setForeground(new java.awt.Color(255, 255, 255));
        btnThemquyen.setText("Thêm quyền");
        btnThemquyen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(242, 242, 242), 3));

        javax.swing.GroupLayout PanPhanquyenLayout = new javax.swing.GroupLayout(PanPhanquyen);
        PanPhanquyen.setLayout(PanPhanquyenLayout);
        PanPhanquyenLayout.setHorizontalGroup(
            PanPhanquyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(PanPhanquyenLayout.createSequentialGroup()
                .addGroup(PanPhanquyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanPhanquyenLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(Nhapten)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNhapten, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(PanPhanquyenLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(PanPhanquyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanPhanquyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txQuanlysach, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Quanlychucnang, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(txQuanlynhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txQuanlyphieunhapsach, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txQuanlydocgia, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txQuanlyphanquyen, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txQuanlyphieumuon, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txQuanlytaikhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txQuanlythongke, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txQuanlynguonnhap, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(100, 100, 100)
                        .addGroup(PanPhanquyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanPhanquyenLayout.createSequentialGroup()
                                .addGroup(PanPhanquyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Quanlynhanvien)
                                    .addComponent(Quanlysach)
                                    .addComponent(Quanlydocgia)
                                    .addComponent(Quanlyphieunhapsach)
                                    .addComponent(Quanlytaikhoan)
                                    .addComponent(Quanlythongke)
                                    .addComponent(Quanlynguonnhap))
                                .addGap(628, 628, 628)
                                .addGroup(PanPhanquyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnCapnhat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnThemquyen, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)))
                            .addGroup(PanPhanquyenLayout.createSequentialGroup()
                                .addGroup(PanPhanquyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Quanlyphanquyen)
                                    .addComponent(Quanlyphieumuon))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        PanPhanquyenLayout.setVerticalGroup(
            PanPhanquyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanPhanquyenLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(PanPhanquyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanPhanquyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(PanPhanquyenLayout.createSequentialGroup()
                            .addGap(353, 353, 353)
                            .addComponent(txQuanlythongke)
                            .addGap(19, 19, 19)
                            .addComponent(txQuanlynguonnhap))
                        .addGroup(PanPhanquyenLayout.createSequentialGroup()
                            .addGroup(PanPhanquyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txQuanlyphieumuon)
                                .addGroup(PanPhanquyenLayout.createSequentialGroup()
                                    .addGroup(PanPhanquyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtNhapten, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Nhapten, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(PanPhanquyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanPhanquyenLayout.createSequentialGroup()
                                            .addGroup(PanPhanquyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanPhanquyenLayout.createSequentialGroup()
                                                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(Quanlychucnang)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(txQuanlysach)
                                                    .addGap(37, 37, 37))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanPhanquyenLayout.createSequentialGroup()
                                                    .addComponent(Quanlysach)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(txQuanlynhanvien))
                                                .addComponent(Quanlynhanvien, javax.swing.GroupLayout.Alignment.TRAILING))
                                            .addGap(18, 18, 18)
                                            .addComponent(txQuanlyphieunhapsach)
                                            .addGap(37, 37, 37))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanPhanquyenLayout.createSequentialGroup()
                                            .addComponent(Quanlyphieunhapsach)
                                            .addGap(18, 18, 18)
                                            .addComponent(txQuanlydocgia))
                                        .addComponent(Quanlydocgia, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addGap(18, 18, 18)
                                    .addGroup(PanPhanquyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txQuanlyphanquyen)
                                        .addComponent(Quanlyphanquyen))
                                    .addGap(18, 18, 18)
                                    .addComponent(Quanlyphieumuon)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(PanPhanquyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanPhanquyenLayout.createSequentialGroup()
                                    .addGroup(PanPhanquyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(Quanlytaikhoan)
                                        .addComponent(txQuanlytaikhoan))
                                    .addGap(25, 25, 25)
                                    .addComponent(btnCapnhat, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(PanPhanquyenLayout.createSequentialGroup()
                                    .addGroup(PanPhanquyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnThemquyen, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Quanlythongke, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addGap(36, 36, 36)))))
                    .addGroup(PanPhanquyenLayout.createSequentialGroup()
                        .addGap(390, 390, 390)
                        .addComponent(Quanlynguonnhap)))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ThemPhanquyenLayout = new javax.swing.GroupLayout(ThemPhanquyen);
        ThemPhanquyen.setLayout(ThemPhanquyenLayout);
        ThemPhanquyenLayout.setHorizontalGroup(
            ThemPhanquyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanPhanquyen, javax.swing.GroupLayout.DEFAULT_SIZE, 1184, Short.MAX_VALUE)
        );
        ThemPhanquyenLayout.setVerticalGroup(
            ThemPhanquyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ThemPhanquyenLayout.createSequentialGroup()
                .addComponent(PanPhanquyen, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 77, Short.MAX_VALUE))
        );

        Giaodien.add(ThemPhanquyen, "Them");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(ThanhChucnang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(Giaodien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(16, 16, 16))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(ThanhChucnang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(Giaodien, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnXemChuyenXem(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemChuyenXem
        CardLayout card = (CardLayout) Giaodien.getLayout();
        card.show(Giaodien, "Xem");
    }//GEN-LAST:event_btnXemChuyenXem

    private void btnThemChuyenThem(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemChuyenThem
        CardLayout card = (CardLayout) Giaodien.getLayout();
        card.show(Giaodien, "Them");
    }//GEN-LAST:event_btnThemChuyenThem

    private void btnChitietChuyenChitiet(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChitietChuyenChitiet
        CardLayout card = (CardLayout) Giaodien.getLayout();
        card.show(Giaodien, "Chitiet");
    }//GEN-LAST:event_btnChitietChuyenChitiet

    private void btnXoaphieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaphieuActionPerformed
        // TODO add your handling code here:
         // Get the selected row from the table
    int selectedRow = tbPhanquyen.getSelectedRow();
    
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Vui lòng chọn một phân quyền để xóa!", 
            "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        return;
    }
    
    try {
        // Get the permission ID from the selected row
        String maPhanQuyen = tbPhanquyen.getValueAt(selectedRow, 0).toString();
        String tenPhanQuyen = tbPhanquyen.getValueAt(selectedRow, 1).toString();
        
        // Confirm deletion with the user
        int confirm = JOptionPane.showConfirmDialog(this, 
            "Bạn có chắc chắn muốn xóa phân quyền \"" + tenPhanQuyen + "\" (Mã: " + maPhanQuyen + ") không?", 
            "Xác nhận xóa", JOptionPane.YES_NO_OPTION);
        
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }
        
        // Create a PhanQuyenDAO instance
        PhanQuyenDAO phanQuyenDAO = new PhanQuyenDAO();
        
        // Check if the permission is assigned to any account
        if (phanQuyenDAO.kiemTraPhanQuyenDangDuocSuDung(maPhanQuyen)) {
            JOptionPane.showMessageDialog(this, 
                "Không thể xóa phân quyền này vì đang được gán cho một hoặc nhiều tài khoản!", 
                "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Delete the permission
        boolean success = phanQuyenDAO.xoaPhanQuyen(maPhanQuyen);
        
        if (success) {
            JOptionPane.showMessageDialog(this, "Xóa phân quyền thành công!");
            
            // Refresh the permissions table
            loadPhanQuyenTable();
        } else {
            JOptionPane.showMessageDialog(this, "Xóa phân quyền thất bại!", 
                "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Lỗi khi xóa phân quyền: " + e.getMessage(), 
            "Lỗi", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }
    }//GEN-LAST:event_btnXoaphieuActionPerformed
 // Add this method to your PhanquyenGUI class
private void btnThemquyenActionPerformed(java.awt.event.ActionEvent evt) {
    try {
        // Get the permission name from the text field
        String tenPhanQuyen = txtNhapten.getText().trim();
        
        // Validate the input name
        if (tenPhanQuyen.isEmpty() || tenPhanQuyen.equals("Nhập tên cho phân quyền")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập tên cho phân quyền!", 
                "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Create a PhanQuyenDAO instance
        PhanQuyenDAO phanQuyenDAO = new PhanQuyenDAO();
        
        // Generate a new permission ID
        String maPhanQuyen = phanQuyenDAO.taoMaPhanQuyenMoi();
        
        // Collect the selected functions (checkboxes)
        ArrayList<String> selectedFunctions = new ArrayList<>();
        
        // Check each function checkbox
        if (Quanlysach.isSelected()) selectedFunctions.add("Q1");
        if (Quanlynhanvien.isSelected()) selectedFunctions.add("Q2");
        if (Quanlyphieunhapsach.isSelected()) selectedFunctions.add("Q3");
        if (Quanlydocgia.isSelected()) selectedFunctions.add("Q4");
        if (Quanlyphanquyen.isSelected()) selectedFunctions.add("Q5");
        if (Quanlyphieumuon.isSelected()) selectedFunctions.add("Q6");
        if (Quanlytaikhoan.isSelected()) selectedFunctions.add("Q7");
        if (Quanlythongke.isSelected()) selectedFunctions.add("Q8");
        if (Quanlynguonnhap.isSelected()) selectedFunctions.add("Q9");
        
        // Validate at least one function is selected
        if (selectedFunctions.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn ít nhất một chức năng!", 
                "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Add the permission with selected functions to the database
        boolean success = true;
        for (String maChucNang : selectedFunctions) {
            PhanQuyenDTO phanQuyen = new PhanQuyenDTO(maPhanQuyen, tenPhanQuyen, maChucNang);
            if (!phanQuyenDAO.themPhanQuyen(phanQuyen)) {
                success = false;
                break;
            }
        }
        
        if (success) {
            JOptionPane.showMessageDialog(this, "Thêm phân quyền thành công!");
            
            // Add the new permission to the table
            DefaultTableModel model = (DefaultTableModel) tbPhanquyen.getModel();
            model.addRow(new Object[]{maPhanQuyen, tenPhanQuyen});
            
            // Reset the form
            resetForm();
            
            // Refresh the permissions table
            loadPhanQuyenTable();
        } else {
            JOptionPane.showMessageDialog(this, "Thêm phân quyền thất bại!", 
                "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Lỗi: " + e.getMessage(), 
            "Lỗi", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }
}

// Add reset form function
private void resetForm() {
    txtNhapten.setText("Nhập tên cho phân quyền");
    
    // Reset all checkboxes
    Quanlysach.setSelected(false);
    Quanlynhanvien.setSelected(false);
    Quanlyphieunhapsach.setSelected(false);
    Quanlydocgia.setSelected(false);
    Quanlyphanquyen.setSelected(false);
    Quanlyphieumuon.setSelected(false);
    Quanlytaikhoan.setSelected(false);
    Quanlythongke.setSelected(false);
    Quanlynguonnhap.setSelected(false);
}

// Add method to load the permissions table
private void loadPhanQuyenTable() {
    try {
        PhanQuyenDAO phanQuyenDAO = new PhanQuyenDAO();
        ArrayList<PhanQuyenDTO> danhSachPhanQuyen = phanQuyenDAO.layDanhSachPhanQuyen();
        
        // Convert to a map to remove duplicates (since one permission can have multiple functions)
        Map<String, String> uniquePermissions = new HashMap<>();
        for (PhanQuyenDTO pq : danhSachPhanQuyen) {
            uniquePermissions.put(pq.getMaPhanQuyen(), pq.getTenPhanQuyen());
        }
        
        // Clear the table
        DefaultTableModel model = (DefaultTableModel) tbPhanquyen.getModel();
        model.setRowCount(0);
        
        // Add each unique permission to the table
        for (Map.Entry<String, String> entry : uniquePermissions.entrySet()) {
            model.addRow(new Object[]{entry.getKey(), entry.getValue()});
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Lỗi khi tải dữ liệu phân quyền: " + e.getMessage(), 
            "Lỗi", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }
}

private void btnChitietChuyenChitietActionPerformed(java.awt.event.ActionEvent evt) {
    // Lấy dòng được chọn từ bảng
    int selectedRow = tbPhanquyen.getSelectedRow();
    
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Vui lòng chọn một phân quyền để xem chi tiết!", 
            "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        return;
    }
    
    try {
        // Lấy mã phân quyền và tên từ dòng đã chọn
        String maPhanQuyen = tbPhanquyen.getValueAt(selectedRow, 0).toString();
        String tenPhanQuyen = tbPhanquyen.getValueAt(selectedRow, 1).toString();
        
        // Sử dụng phương thức có sẵn để lấy danh sách chức năng của phân quyền này
        PhanQuyenDAO phanQuyenDAO = new PhanQuyenDAO();
        ArrayList<PhanQuyenDTO> danhSachPhanQuyen = phanQuyenDAO.layDanhSachPhanQuyenTheoMa(maPhanQuyen);
        
        // Tạo thông điệp với thông tin phân quyền
        StringBuilder message = new StringBuilder();
        message.append("Mã phân quyền: ").append(maPhanQuyen).append("\n");
        message.append("Tên phân quyền: ").append(tenPhanQuyen).append("\n\n");
        message.append("Các chức năng:\n");
        
        // Thêm từng chức năng vào thông điệp
        for (PhanQuyenDTO pq : danhSachPhanQuyen) {
            String tenChucNang = getTenChucNang(pq.getMaChucNang());
            message.append("- ").append(tenChucNang).append(" (").append(pq.getMaChucNang()).append(")\n");
        }
        
        
        JOptionPane.showMessageDialog(null, message.toString(), 
            "Chi tiết phân quyền", JOptionPane.INFORMATION_MESSAGE);
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Lỗi khi hiển thị chi tiết phân quyền: " + e.getMessage(), 
            "Lỗi", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }
}

// Phương thức hỗ trợ để lấy tên chức năng từ mã chức năng
private String getTenChucNang(String maChucNang) {
    switch (maChucNang) {
        case "Q1": return "Quản lý sách";
        case "Q2": return "Quản lý nhân viên";
        case "Q3": return "Quản lý phiếu nhập sách";
        case "Q4": return "Quản lý độc giả";
        case "Q5": return "Quản lý phân quyền";
        case "Q6": return "Quản lý phiếu mượn";
        case "Q7": return "Quản lý tài khoản";
        case "Q8": return "Quản lý thống kê";
        case "Q9": return "Quản lý nguồn nhập";
        default: return "Chức năng không xác định";
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Giaodien;
    private javax.swing.JLabel Nhapten;
    private javax.swing.JPanel PanPhanquyen;
    private javax.swing.JLabel Quanlychucnang;
    private javax.swing.JCheckBox Quanlydocgia;
    private javax.swing.JCheckBox Quanlynguonnhap;
    private javax.swing.JCheckBox Quanlynhanvien;
    private javax.swing.JCheckBox Quanlyphanquyen;
    private javax.swing.JCheckBox Quanlyphieumuon;
    private javax.swing.JCheckBox Quanlyphieunhapsach;
    private javax.swing.JCheckBox Quanlysach;
    private javax.swing.JCheckBox Quanlytaikhoan;
    private javax.swing.JCheckBox Quanlythongke;
    private javax.swing.JPanel ThanhChucnang;
    private javax.swing.JPanel ThemPhanquyen;
    private javax.swing.JPanel XemPhanquyen;
    private javax.swing.JButton btnCapnhat;
    private javax.swing.JButton btnChitiet;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThemquyen;
    private javax.swing.JButton btnXem;
    private javax.swing.JButton btnXoaphieu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable tbPhanquyen;
    private javax.swing.JLabel txQuanlydocgia;
    private javax.swing.JLabel txQuanlynguonnhap;
    private javax.swing.JLabel txQuanlynhanvien;
    private javax.swing.JLabel txQuanlyphanquyen;
    private javax.swing.JLabel txQuanlyphieumuon;
    private javax.swing.JLabel txQuanlyphieunhapsach;
    private javax.swing.JLabel txQuanlysach;
    private javax.swing.JLabel txQuanlytaikhoan;
    private javax.swing.JLabel txQuanlythongke;
    private javax.swing.JTextField txtNhapten;
    // End of variables declaration//GEN-END:variables
}
